// FRONTEND INTEGRATION GUIDE
// ============================================
// 
// This file shows how to use the new contract client, DTN manager, 
// and helper utilities together to integrate smart contracts into the BlockVote frontend.
//
// Key Components:
// 1. contractClient.ts - Smart contract interaction
// 2. dtnManager.ts - Offline-first vote queuing
// 3. helpers.ts - Utility functions
// 4. constants.ts - Configuration
// 5. types.ts - TypeScript definitions

import { ContractClient } from "@/lib/contractClient";
import { getDTNManager } from "@/lib/dtnManager";
import {
  generateMerkleRoot,
  generateMerkleProof,
  generateNullifier,
  hashAadhaar,
  isValidAadhaar,
  formatTimestamp,
  maskSensitive,
} from "@/lib/helpers";
import {
  WhitelistEntry,
  VoteRecord,
  ElectionState,
  ContractResponse,
} from "@/lib/types";
import { STORAGE_KEYS, ELECTION_CONFIG, debugLog } from "@/lib/constants";

/**
 * ============================================
 * INTEGRATION PATTERNS
 * ============================================
 */

/**
 * PATTERN 1: Admin Panel - Initialize Election
 *
 * When admin sets up election:
 * 1. Generate merkle root from registered voters
 * 2. Call smart contract to initialize election
 * 3. Save election state to admin
 *
 * Usage location: rofv-ui/app/admin/page.tsx
 */

export async function initializeElectionOnBlockchain(
  whitelist: WhitelistEntry[],
  contractClient: ContractClient
): Promise<ContractResponse> {
  try {
    debugLog("ADMIN", "Starting election initialization");

    // Step 1: Generate merkle root
    const merkleRoot = await generateMerkleRoot(whitelist);
    debugLog("ADMIN", "Generated merkle root", { root: maskSensitive(merkleRoot) });

    // Step 2: Call contract
    const response = await contractClient.initializeElection(
      merkleRoot,
      ELECTION_CONFIG.TOTAL_CANDIDATES,
      whitelist.length
    );

    if (!response.success) {
      throw new Error(response.error || "Contract initialization failed");
    }

    // Step 3: Save election state
    if (response.data?.electionStatePubkey) {
      localStorage.setItem(
        STORAGE_KEYS.ELECTION_STATE,
        response.data.electionStatePubkey.toBase58()
      );
      localStorage.setItem(STORAGE_KEYS.MERKLE_ROOT, merkleRoot);
    }

    debugLog("ADMIN", "Election initialized successfully");
    return response;
  } catch (error) {
    console.error("Election initialization failed:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

/**
 * PATTERN 2: Polling Booth - Cast Vote with DTN Queue
 *
 * When voter casts vote:
 * 1. Generate nullifier (prevents double voting)
 * 2. Generate merkle proof (proves voter eligibility)
 * 3. Create vote record
 * 4. Queue in DTN if offline, or submit to blockchain
 * 5. Update whitelist with hasVoted=true immediately
 *
 * Usage location: rofv-ui/app/booth/vote/page.tsx
 */

export async function castVoteWithQueue(
  voterAadhaar: string,
  candidateId: number,
  candidateName: string,
  whitelist: WhitelistEntry[],
  contractClient: ContractClient
): Promise<{ queueId?: string; transactionSignature?: string; error?: string }> {
  try {
    debugLog("VOTE", "Starting vote process for voter", { aadhaar: maskSensitive(voterAadhaar) });

    const dtnManager = getDTNManager();

    // Step 1: Validate inputs
    const voterEntry = whitelist.find((v) => v.aadhaar === voterAadhaar);
    if (!voterEntry) {
      throw new Error("Voter not found in whitelist");
    }

    if (voterEntry.hasVoted) {
      throw new Error("Voter has already voted");
    }

    // CRITICAL: Mark hasVoted immediately (before any async operations)
    // This ensures admin sees voter participation in real-time
    voterEntry.hasVoted = true;
    voterEntry.votedAt = new Date().toISOString();
    voterEntry.votedCandidate = candidateName;
    localStorage.setItem(STORAGE_KEYS.WHITELIST, JSON.stringify(whitelist));
    debugLog("VOTE", "Marked voter as voted in whitelist");

    // Step 2: Generate nullifier (unique identifier for this voter)
    const nullifier = await generateNullifier(voterAadhaar);
    debugLog("VOTE", "Generated nullifier", { nullifier: maskSensitive(nullifier) });

    // Step 3: Generate merkle proof (proves voter is registered)
    const merkleProof = await generateMerkleProof(whitelist, voterAadhaar);
    debugLog("VOTE", "Generated merkle proof", { proofLength: merkleProof.length });

    // Step 4: Create vote record
    const voteRecord: VoteRecord = {
      voterAadhaar: await hashAadhaar(voterAadhaar),
      candidateId,
      candidateName,
      nullifier,
      zeroKnowledgeProof: {
        proof: "mock_proof", // Would be generated by snarkjs in production
        publicSignals: [],
      },
      timestamp: new Date().toISOString(),
      encrypted: false, // Would be RSA-4096 encrypted in production
    };

    // Step 5: Try to submit to blockchain, or queue if offline
    if (!dtnManager.isOnline()) {
      // Offline: Add to DTN queue
      debugLog("VOTE", "Network offline, queuing vote in DTN");
      const queueItem = dtnManager.addVoteToQueue(voteRecord);
      dtnManager.setNetworkStatus("offline");
      return { queueId: queueItem.id };
    } else {
      // Online: Submit to blockchain
      debugLog("VOTE", "Network online, submitting to blockchain");
      const response = await contractClient.castVote(
        candidateId,
        nullifier,
        merkleProof,
        voteRecord.zeroKnowledgeProof
      );

      if (!response.success) {
        // Contract call failed - queue for retry
        debugLog("VOTE", "Contract submission failed, queuing for retry");
        const queueItem = dtnManager.addVoteToQueue(voteRecord);
        return { queueId: queueItem.id, error: "Queued for retry" };
      }

      debugLog("VOTE", "Vote submitted successfully to blockchain");
      return { transactionSignature: response.transactionSignature };
    }
  } catch (error) {
    console.error("Vote casting failed:", error);

    // If error occurred after marking hasVoted, we need to revert it
    const voterEntry = whitelist.find((v) => v.aadhaar === voterAadhaar);
    if (voterEntry && voterEntry.hasVoted) {
      voterEntry.hasVoted = false;
      delete voterEntry.votedAt;
      delete voterEntry.votedCandidate;
      localStorage.setItem(STORAGE_KEYS.WHITELIST, JSON.stringify(whitelist));
      debugLog("VOTE", "Reverted hasVoted flag due to error");
    }

    return { error: error instanceof Error ? error.message : "Unknown error" };
  }
}

/**
 * PATTERN 3: Admin Dashboard - Display Real-time Status
 *
 * When displaying admin dashboard:
 * 1. Fetch current vote tally from blockchain
 * 2. Show whitelist with voter status
 * 3. Show DTN queue status
 * 4. Listen for updates and refresh
 *
 * Usage location: rofv-ui/app/admin/page.tsx
 */

export async function fetchElectionStatus(
  contractClient: ContractClient
): Promise<{
  voteTally?: any[];
  electionState?: ElectionState;
  error?: string;
}> {
  try {
    debugLog("ADMIN", "Fetching election status from blockchain");

    const tally = await contractClient.getVoteTally();
    debugLog("ADMIN", "Fetched vote tally", { candidates: tally?.length });

    return { voteTally: tally };
  } catch (error) {
    console.error("Failed to fetch election status:", error);
    return { error: error instanceof Error ? error.message : "Unknown error" };
  }
}

/**
 * PATTERN 4: DTN Queue Sync
 *
 * When network comes back online:
 * 1. Get all pending items from DTN queue
 * 2. Try to submit each to blockchain
 * 3. Mark as confirmed or failed
 * 4. Update UI
 *
 * Usage location: Any component that needs to sync
 */

export async function syncDTNQueue(
  contractClient: ContractClient,
  onProgress?: (status: string) => void
): Promise<{ synced: number; failed: number }> {
  try {
    const dtnManager = getDTNManager();
    const pending = dtnManager.getPendingItems();

    debugLog("DTN", `Starting DTN sync with ${pending.length} pending items`);

    let synced = 0;
    let failed = 0;

    for (const queueItem of pending) {
      if (onProgress) {
        onProgress(`Syncing vote ${synced + 1}/${pending.length}...`);
      }

      try {
        // Mark as submitted
        dtnManager.markAsSubmitted(queueItem.id);

        // Submit to blockchain
        const response = await contractClient.castVote(
          queueItem.vote.candidateId,
          queueItem.vote.nullifier,
          [], // merkleProof would come from queueItem.vote
          queueItem.vote.zeroKnowledgeProof
        );

        if (response.success && response.transactionSignature) {
          // Mark as confirmed
          dtnManager.markAsConfirmed(queueItem.id, response.transactionSignature);
          synced++;
          debugLog("DTN", `Confirmed vote ${queueItem.id}`);
        } else {
          // Mark as failed
          dtnManager.markAsFailed(queueItem.id, response.error || "Unknown error");
          failed++;
          debugLog("DTN", `Failed to sync vote ${queueItem.id}`);
        }
      } catch (error) {
        dtnManager.markAsFailed(
          queueItem.id,
          error instanceof Error ? error.message : "Unknown error"
        );
        failed++;
        debugLog("DTN", `Error syncing vote ${queueItem.id}:`, error);
      }
    }

    debugLog("DTN", `Sync complete: ${synced} synced, ${failed} failed`);
    return { synced, failed };
  } catch (error) {
    console.error("DTN sync failed:", error);
    return { synced: 0, failed: -1 };
  }
}

/**
 * PATTERN 5: Contract Client Setup in React Component
 *
 * Usage in a React component:
 */

export function useContractClient() {
  // In actual component, use like this:
  /*
  import { useWallet } from "@solana/wallet-adapter-react";
  import { useEffect, useState } from "react";
  
  const { publicKey, signTransaction, connected } = useWallet();
  const [contractClient, setContractClient] = useState<ContractClient | null>(null);
  
  useEffect(() => {
    if (connected && publicKey && signTransaction) {
      const client = new ContractClient({
        wallet: {
          publicKey,
          signTransaction,
        },
      });
      setContractClient(client);
      
      debugLog("APP", "Contract client initialized");
    }
  }, [connected, publicKey, signTransaction]);
  
  return contractClient;
  */
}

/**
 * ============================================
 * EXAMPLE COMPONENT INTEGRATION
 * ============================================
 */

/**
 * Example: Admin Panel Integration
 *
 * In: rofv-ui/app/admin/page.tsx
 *
 * Add this to the component:
 */

// import { ContractClient } from "@/lib/contractClient";
// import { useWallet } from "@solana/wallet-adapter-react";
// import { useEffect, useState } from "react";
//
// export default function AdminPanel() {
//   const { connected, publicKey, signTransaction } = useWallet();
//   const [contractClient, setContractClient] = useState<ContractClient | null>(null);
//
//   useEffect(() => {
//     if (connected && publicKey && signTransaction) {
//       const client = new ContractClient({ wallet: { publicKey, signTransaction } });
//       setContractClient(client);
//     }
//   }, [connected, publicKey, signTransaction]);
//
//   const handleInitializeElection = async () => {
//     if (!contractClient) return;
//     const whitelist = JSON.parse(localStorage.getItem("whitelist") || "[]");
//     const result = await initializeElectionOnBlockchain(whitelist, contractClient);
//     if (result.success) {
//       alert("Election initialized on blockchain!");
//     }
//   };
//
//   return (
//     <div>
//       <button onClick={handleInitializeElection}>
//         Initialize Election on Blockchain
//       </button>
//     </div>
//   );
// }

/**
 * Example: Polling Booth Vote Integration
 *
 * In: rofv-ui/app/booth/vote/page.tsx
 *
 * Add this to the vote submission handler:
 */

// const handleSubmitVote = async () => {
//   const result = await castVoteWithQueue(
//     voterAadhaar,
//     selectedCandidateId,
//     selectedCandidateName,
//     whitelist,
//     contractClient
//   );
//
//   if (result.transactionSignature) {
//     alert("Vote submitted to blockchain!");
//   } else if (result.queueId) {
//     alert("Vote queued. Will be submitted when online.");
//   } else {
//     alert(`Error: ${result.error}`);
//   }
// };

/**
 * Example: DTN Sync Setup
 *
 * In: rofv-ui/app/layout.tsx or main component
 *
 * Add this for automatic syncing when connection comes back:
 */

// useEffect(() => {
//   const dtnManager = getDTNManager();
//
//   const handleSync = async () => {
//     if (contractClient) {
//       await syncDTNQueue(contractClient, (status) => {
//         console.log(status);
//       });
//     }
//   };
//
//   dtnManager.onSyncRequired(handleSync);
// }, [contractClient]);

/**
 * ============================================
 * CHECKLIST FOR INTEGRATION
 * ============================================
 */

/**
 * ✅ ADMIN PANEL (rofv-ui/app/admin/page.tsx)
 * 
 * [ ] Import ContractClient and helpers
 * [ ] Initialize contract client in useEffect
 * [ ] Add "Initialize Election" button
 * [ ] Call initializeElectionOnBlockchain() when clicked
 * [ ] Display election state from blockchain
 * [ ] Show vote tally real-time
 * [ ] Show DTN queue status
 * [ ] Add refresh button for manual sync
 */

/**
 * ✅ POLLING BOOTH (rofv-ui/app/booth/vote/page.tsx)
 * 
 * [ ] Import ContractClient and castVoteWithQueue
 * [ ] Initialize contract client
 * [ ] Add vote submission handler
 * [ ] Call castVoteWithQueue() when voter confirms
 * [ ] Show success/queue message to voter
 * [ ] Handle offline scenario gracefully
 * [ ] Show DTN status if offline
 */

/**
 * ✅ LAYOUT/APP (rofv-ui/app/layout.tsx)
 * 
 * [ ] Setup DTN sync trigger in useEffect
 * [ ] Listen for online/offline events
 * [ ] Show network status to user
 * [ ] Call syncDTNQueue() when online
 */

/**
 * ✅ ENVIRONMENT VARIABLES (.env.local)
 * 
 * [ ] NEXT_PUBLIC_SOLANA_CLUSTER=devnet
 * [ ] NEXT_PUBLIC_ROFV_PROGRAM_ID=<your-program-id>
 * [ ] NEXT_PUBLIC_USE_MOCK_PROOFS=true  (for development)
 * [ ] NEXT_PUBLIC_TEST_MODE=false
 */

/**
 * ============================================
 * COMMON QUESTIONS
 * ============================================
 */

/**
 * Q: What if voter is offline when voting?
 * A: Vote is added to DTN queue. When online, syncDTNQueue() will submit it.
 *
 * Q: What if network drops during vote submission?
 * A: markAsSubmitted() is called first, then retried when online again.
 *
 * Q: How do I know vote is confirmed on blockchain?
 * A: Check DTN queue item status - "confirmed" means it's on blockchain.
 *
 * Q: Can voter vote twice?
 * A: No - nullifier prevents it. Contract rejects if nullifier was used.
 *    Also whitelist hasVoted flag prevents UI-level double voting.
 *
 * Q: How do I see what's in the DTN queue?
 * A: Call getDTNManager().exportQueue() in browser console for debug output.
 *
 * Q: Where does vote get encrypted?
 * A: In castVoteWithQueue() before creating VoteRecord.
 *    Uses RSA-4096 public key from election state.
 */

export default {};
