/**
 * ZK Proof Generator Service
 * 
 * Generates SNARK proofs client-side for voter eligibility without revealing:
 * - Voter ID (Aadhar)
 * - Secret PIN
 * - Merkle tree path
 * 
 * Outputs a proof + public signals that the Solana contract can verify
 */

// Dynamic import to avoid TypeScript issues with snarkjs
// @ts-ignore
const snarkjs = require("snarkjs");

export interface ZKProofOutput {
  proof: any;
  publicSignals: string[];
  proofString: string; // Serialized proof for JSON
}

export interface VoterAuthInputs {
  voterId: string;           // User's Aadhar ID (private)
  secretPin: string;         // User's biometric PIN (private)
  merkleRoot: string;        // Public merkle tree root of eligible voters
  electionId: string;        // Which election (public)
  pathElements: string[];    // Merkle proof path (private)
  pathIndices: number[];     // Left/right path indices (private)
}

/**
 * Convert a string (like election ID) to a numeric hash
 * This is needed because BigInt() only works with numeric strings
 */
export const stringToNumericHash = (str: string): string => {
  let hash = 0n;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31n + BigInt(str.charCodeAt(i))) & ((1n << 256n) - 1n);
  }
  return hash.toString();
};

/**
 * Load WASM and ZKey artifacts from specified paths
 * These files are generated by compile.sh in zk-circuits/
 */
export const loadCircuitArtifacts = async (wasmPath: string, zkeyPath: string) => {
  try {
    const wasmResponse = await fetch(wasmPath);
    const wasmBuffer = await wasmResponse.arrayBuffer();
    
    const zkeyResponse = await fetch(zkeyPath);
    const zkeyBuffer = await zkeyResponse.arrayBuffer();
    
    return { wasmBuffer, zkeyBuffer };
  } catch (error) {
    console.error("Failed to load circuit artifacts:", error);
    throw new Error("Circuit artifacts not available. Ensure compile.sh has been run.");
  }
};

/**
 * Generate a ZK SNARK proof that voter is eligible to vote
 * without revealing their identity or private merkle path
 */
export const generateVoterProof = async (
  inputs: VoterAuthInputs,
  wasmBuffer: ArrayBuffer,
  zkeyBuffer: ArrayBuffer
): Promise<ZKProofOutput> => {
  try {
    // Prepare circuit inputs - all in BigInt format for circom
    // Election ID needs to be converted from string to numeric hash
    const circuitInputs = {
      voterId: BigInt(inputs.voterId),
      secretPin: BigInt(inputs.secretPin),
      merkleRoot: BigInt(inputs.merkleRoot),
      electionId: BigInt(stringToNumericHash(inputs.electionId)),
      pathElements: inputs.pathElements.map((pe) => BigInt(pe)),
      pathIndices: inputs.pathIndices.map((pi) => BigInt(pi)),
    };

    // Call wtns generation (witness)
    const witnessBuffer = await snarkjs.wtns.calculate(
      circuitInputs,
      wasmBuffer,
      null
    );

    // Generate the actual SNARK proof using Groth16
    const { proof, publicSignals } = await snarkjs.groth16.prove(
      zkeyBuffer,
      witnessBuffer
    );

    // Serialize proof to JSON string for transmission
    const proofString = JSON.stringify(proof);

    return {
      proof,
      publicSignals,
      proofString,
    };
  } catch (error) {
    console.error("Failed to generate ZK proof:", error);
    throw new Error("Proof generation failed: " + (error as any).message);
  }
};

/**
 * Verify a ZK proof client-side (optional, for testing)
 * Normally the Solana contract performs this verification
 */
export const verifyProofClientSide = async (
  proof: any,
  publicSignals: string[],
  verificationKeyJson: string
): Promise<boolean> => {
  try {
    const verificationKey = JSON.parse(verificationKeyJson);
    const isValid = await snarkjs.groth16.verify(
      verificationKey,
      publicSignals,
      proof
    );
    return isValid;
  } catch (error) {
    console.error("Client-side verification failed:", error);
    return false;
  }
};

/**
 * Mock proof generator for DEMONSTRATION without compiled artifacts
 * Creates a realistic proof structure for UI/UX testing
 */
export const generateMockProof = (inputs: VoterAuthInputs): ZKProofOutput => {
  // Generate fake but realistic-looking proof
  const fakeProof = {
    pi_a: [
      "12345678901234567890123456789012345678901234567890",
      "98765432109876543210987654321098765432109876543210",
      "1",
    ],
    pi_b: [
      [
        "11111111111111111111111111111111111111111111111111",
        "22222222222222222222222222222222222222222222222222",
      ],
      [
        "33333333333333333333333333333333333333333333333333",
        "44444444444444444444444444444444444444444444444444",
      ],
      ["1", "0"],
    ],
    pi_c: [
      "55555555555555555555555555555555555555555555555555",
      "66666666666666666666666666666666666666666666666666",
      "1",
    ],
    protocol: "groth16",
    curve: "bn128",
  };

  // Public signals: [merkleRoot, electionId, nullifierHash]
  // Convert election ID to numeric hash for consistency with real proof
  const electionIdNumeric = stringToNumericHash(inputs.electionId);
  const mockNullifier = BigInt(inputs.voterId) ^ BigInt(electionIdNumeric); // XOR for demo
  const publicSignals = [
    inputs.merkleRoot,
    electionIdNumeric,
    mockNullifier.toString(),
  ];

  return {
    proof: fakeProof,
    publicSignals,
    proofString: JSON.stringify(fakeProof),
  };
};

/**
 * Calculate merkle tree path for a voter (mock implementation)
 * In production, this comes from the backend/contract
 */
export const calculateMerkleProof = (
  voterId: string,
  treeDepth: number = 20
): { pathElements: string[]; pathIndices: number[] } => {
  // Mock: Generate pseudo-random path for demonstration
  const pathElements: string[] = [];
  const pathIndices: number[] = [];

  for (let i = 0; i < treeDepth; i++) {
    // Generate fake merkle proof hashes (would be real hashes in production)
    const hash = BigInt(voterId) * BigInt(i + 1);
    pathElements.push(hash.toString());
    pathIndices.push(Math.random() > 0.5 ? 1 : 0);
  }

  return { pathElements, pathIndices };
};
